"""
This function takes the data generated by Counterpoint.py and CantusFirmi.py and turns it into a scatterplot.
While the machine could output the data as raw numbers in an array, a scatterplot is a much more human readable format
for displaying the results.
"""

# This function requires the ability to graph
from matplotlib import pyplot

def Graph(Version, Species, Mode, Counterpoint, Cantus):
    Pitches = [i for i in range(len(Counterpoint))]

    print(Pitches)
    print(Cantus)
    print(Counterpoint)

    pyplot.scatter(Pitches, Counterpoint)
    pyplot.scatter(Pitches, Cantus)
    pyplot.title(Version + ": " + "Species " + str(Species) + " in " + Mode + " Mode")
    pyplot.show()